# Generated by Django 3.2.5 on 2022-02-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicien',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='photo_oda')),
                ('statut', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now=True)),
                ('heure_paiement', models.TimeField(auto_now=True)),
                ('id_academicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odacagnotte.academicien')),
                ('id_motif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odacagnotte.motif')),
            ],
        ),
    ]
